spring:
  ai:
    azure:
      openai:
        api-key:
        endpoint:
        chat:
          options:
            deployment-name: gpt-4o
        image:
          options:
            deployment-name: dall-e-3