import {USColorScheme} from 'styled-components';
import {USPalette} from "@designsystem/foundation/color/USPalette";

export const USLightScheme: USColorScheme = Object.freeze({
    textNormal: USPalette.Neutral90,
    textDarken: USPalette.Neutral80,
    textAlt: USPalette.Neutral50,
    textInverse: USPalette.Neutral10,
    textDisabled: USPalette.Neutral40,
    textWarning: USPalette.Red70,
    buttonPrimary: USPalette.Primary60,
    buttonPrimaryPressed: USPalette.Primary80,
    buttonPrimaryDisabled: USPalette.Neutral20,
    buttonText: USPalette.Neutral90,
    buttonTextDisabled: USPalette.Neutral40,
    tabButtonPrimary: USPalette.Neutral90,
    radioButtonPrimary: USPalette.Neutral90,
    radioButtonPrimaryDisabled: USPalette.Neutral40,
    radioButtonSecondary: USPalette.Neutral70,
    radioButtonSecondaryDisabled: USPalette.Neutral50,
    background: USPalette.Neutral00,
    backgroundAlt: USPalette.Neutral10,
    backgroundInverse: USPalette.Neutral80,
    github: '#24292E',
    baekjoon: '#0076C0',
    dividerNormal: USPalette.Neutral20,
    textFieldIcon: USPalette.Neutral90,
    textFieldIconDisabled: USPalette.Neutral50,
    textFieldPrimary: USPalette.Primary80,
    textFieldSecondary: USPalette.Neutral30,
    textFieldSecondaryDisabled: USPalette.Neutral20,
    textFieldTextDisabled: USPalette.Neutral40,
    avatarLabel: USPalette.Neutral30,
    avatarBackground: USPalette.Neutral20,
    elevationBlack1: 'rgba(0, 0, 0, 0.02)',
    elevationBlack2: 'rgba(0, 0, 0, 0.04)',
    elevationBlack3: 'rgba(0, 0, 0, 0.06)',
    bottomTabPrimary: USPalette.Neutral70,
    bottomTabPrimaryDisabled: USPalette.Neutral40,
    bottomTabSecondary: USPalette.Neutral30,
    likePrimary: USPalette.Red60,
    likePrimaryDisabled: USPalette.Neutral40,
    likeSecondary: USPalette.Red10,
    likeSecondaryDisabled: USPalette.Neutral20,
});

export const USDarkScheme: USColorScheme = {
    textNormal: USPalette.Neutral10,
    textDarken: USPalette.Neutral50,
    textAlt: USPalette.Neutral60,
    textInverse: USPalette.Neutral10,
    textDisabled: USPalette.Neutral40,
    textWarning: USPalette.Red60,
    buttonPrimary: USPalette.Primary60,
    buttonPrimaryPressed: USPalette.Primary80,
    buttonPrimaryDisabled: USPalette.Neutral70,
    buttonText: USPalette.Neutral90,
    buttonTextDisabled: USPalette.Neutral60,
    tabButtonPrimary: USPalette.Primary60,
    radioButtonPrimary: USPalette.Primary60,
    radioButtonPrimaryDisabled: USPalette.Neutral60,
    radioButtonSecondary: USPalette.Neutral20,
    radioButtonSecondaryDisabled: USPalette.Neutral50,
    background: USPalette.Neutral80,
    backgroundAlt: USPalette.Neutral90,
    backgroundInverse: USPalette.Neutral00,
    github: USPalette.Neutral10,
    baekjoon: USPalette.Neutral10,
    dividerNormal: USPalette.Neutral70,
    textFieldIcon: USPalette.Primary60,
    textFieldIconDisabled: USPalette.Primary30,
    textFieldPrimary: USPalette.Primary80,
    textFieldSecondary: USPalette.Neutral70,
    textFieldSecondaryDisabled: USPalette.Neutral70,
    textFieldTextDisabled: USPalette.Neutral70,
    avatarLabel: USPalette.Neutral80,
    avatarBackground: USPalette.Neutral70,
    elevationBlack1: 'rgba(204, 204, 214, 0.02)',
    elevationBlack2: 'rgba(204, 204, 214, 0.04)',
    elevationBlack3: 'rgba(204, 204, 214, 0.06)',
    bottomTabPrimary: USPalette.Primary40,
    bottomTabPrimaryDisabled: USPalette.Neutral60,
    bottomTabSecondary: USPalette.Neutral70,
    likePrimary: USPalette.Red60,
    likePrimaryDisabled: USPalette.Neutral40,
    likeSecondary: USPalette.Transparent,
    likeSecondaryDisabled: USPalette.Neutral80,
}